// Generated by gencpp from file hrg_camera/CameraStatusResponse.msg
// DO NOT EDIT!


#ifndef HRG_CAMERA_MESSAGE_CAMERASTATUSRESPONSE_H
#define HRG_CAMERA_MESSAGE_CAMERASTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrg_camera
{
template <class ContainerAllocator>
struct CameraStatusResponse_
{
  typedef CameraStatusResponse_<ContainerAllocator> Type;

  CameraStatusResponse_()
    : response()  {
    }
  CameraStatusResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CameraStatusResponse_

typedef ::hrg_camera::CameraStatusResponse_<std::allocator<void> > CameraStatusResponse;

typedef boost::shared_ptr< ::hrg_camera::CameraStatusResponse > CameraStatusResponsePtr;
typedef boost::shared_ptr< ::hrg_camera::CameraStatusResponse const> CameraStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrg_camera::CameraStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrg_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::hrg_camera::CameraStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrg_camera/CameraStatusResponse";
  }

  static const char* value(const ::hrg_camera::CameraStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n\
\n\
";
  }

  static const char* value(const ::hrg_camera::CameraStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrg_camera::CameraStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrg_camera::CameraStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRG_CAMERA_MESSAGE_CAMERASTATUSRESPONSE_H
